main: ru.sgk.reportmanager.ReportManager
name: ReportManager
version: 0.0.3-SNAPSHOT
authors: [SteveGrKek,yiaaanni]
commands:
  report:
    usage: 'report <nickname> [reason]'
  reports:
    usage: 'reports'

  reportmanager:
    description: 'for server developer'
    aliases: [rm]
    usage: '/<command> reload'
