# Плагин написал SteveGrKek.
# Если есть замечания по плагину,
# пишите в ВК - https://vk.com/muravchik_as
# или дискорд - SteveGrKek#8031 (в дискорд захожу редко)
#    
# Замечание по плейсхолдерам:
# В каждом поле вы можете использовать ТОЛЬКО те плейсхолдеры, которые есть в ЭТОМ ЖЕ поле
# Формат вывода репортов
format:
  # Формат вывода жалоб на игрока
  player:
  - '&cЖалоба &b#%id%'
  - '&cна пользователя &b%playername%'
  - '&cот &b%reporter%:'
  - '&fЖалоба:'
  - '%text%'
  - '&cОтвет: &b%respond%'
  - '&cОтветил: %admin%'
  - =================================
  # Формат вывода жалоб по какой-то конкретной теме
  theme:
  - '&cЖалоба &b#%id%'
  - '&cна тему &b%playername%:'
  - '&cот &b%reporter%:'
  - '&fЖалоба:'
  - '%text%'
  - '&cОтвет: &b%respond%'
  - '&cОтветил: %admin%'
  - =================================
# Данные для подключения к базе данных (MYSQL)
database:
  host: localhost       # Адрес сервера
  database: database    # Название базы данных
  user: root            # Имя пользователя
  password: ''          # Пароль

# сообщения
messages:
  wrong-text: '&cВы не ввели текст жалобы!'
  response-sended: '&aОтвет по ID &c%id% &aбыл отправлен.'
  notification: '&fБыл получен ответ на вашу жалобу! Введите /report -mylist что бы посмотреть его.'
  notify-admin: 'Была отправлена новая жалоба! Введие /report -get %id% или /report -list, что бы посмотреть полный список жалоб.'
  report-sended: '&aВаша жалоба была успешно отправлена. Id жалобы &c%id%.'
  wrong-text: '&cВы не ввели текст жалобы!'
  wrong-id: '&cНеверный ID жалобы!'
  no-reports: '&fАктивных жалоб нет.'
  no-report: '&cЖалоба с id %id% не найдена!'